# Generated by Django 3.0.6 on 2020-05-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Жанр')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('death_date', models.DateField(blank=True, verbose_name='Дата смерти')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='star_images', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Участник съёмок',
                'verbose_name_plural': 'Участники съёмок',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('tagline', models.CharField(blank=True, max_length=100, verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Постер')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('actors', models.ManyToManyField(related_name='as_actor', to='movies.Person', verbose_name='Актёры')),
                ('directors', models.ManyToManyField(related_name='as_director', to='movies.Person', verbose_name='Режиссёры')),
                ('genres', models.ManyToManyField(related_name='Жанры', to='movies.Genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
