# Generated by Django 3.0.6 on 2020-05-17 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200517_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gallery',
        ),
        migrations.AddField(
            model_name='gallery',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='movies.Movie'),
        ),
    ]
